# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repository',
            new_name='RemoteRepository',
        ),
        migrations.RenameField(
            model_name='remoterepository',
            old_name='repository_name',
            new_name='name',
        ),
    ]
