# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BaseXMLFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.BaseFile')),
            ],
            bases=('files.basefile',),
        ),
        migrations.CreateModel(
            name='HiddenFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.BaseFile')),
            ],
            bases=('files.basefile',),
        ),
        migrations.CreateModel(
            name='MarkdownFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.BaseFile')),
            ],
            bases=('files.basefile',),
        ),
        migrations.CreateModel(
            name='UnparsableXMLFile',
            fields=[
                ('basexmlfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.BaseXMLFile')),
            ],
            bases=('files.basexmlfile',),
        ),
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('basexmlfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.BaseXMLFile')),
            ],
            bases=('files.basexmlfile',),
        ),
    ]
