# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateXMLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('<property object at 0x7f1b5e13aef8>', '<property object at 0x7f1b5e13aef8>'), ('<property object at 0x7f1b5e13aef8>', '<property object at 0x7f1b5e13aef8>'), ('<property object at 0x7f1b5e13aef8>', '<property object at 0x7f1b5e13aef8>'), ('<property object at 0x7f1b5e13aef8>', '<property object at 0x7f1b5e13aef8>')], max_length=100)),
                ('template_file', models.FileField(upload_to='templates/')),
            ],
        ),
    ]
