# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatexmlfile',
            name='file_type',
            field=models.CharField(choices=[('TEIPlace', 'TEIPlace'), ('TEIPerson', 'TEIPerson'), ('TEIWork', 'TEIWork'), ('TEIManuscript', 'TEIManuscript')], max_length=100),
        ),
    ]
