# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_templatexmlfile_template_for_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedxmlfile',
            name='type_string',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
