# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_edit_forms', '0002_auto_20170116_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmleditfield',
            old_name='config_string',
            new_name='xpath',
        ),
        migrations.RemoveField(
            model_name='xmleditfield',
            name='field',
        ),
        migrations.RemoveField(
            model_name='xmleditfield',
            name='field_type',
        ),
        migrations.AddField(
            model_name='xmleditfield',
            name='edit_action',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xmleditfield',
            name='text_generation',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
