# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_edit_forms', '0004_auto_20170226_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmleditfield',
            name='edit_action',
            field=models.CharField(help_text='Whether the generated text should be appended to the node or replace it.', max_length=50),
        ),
        migrations.AlterField(
            model_name='xmleditfield',
            name='text_generation',
            field=models.CharField(help_text='The function used to generate text.', max_length=50),
        ),
        migrations.AlterField(
            model_name='xmleditfield',
            name='xpath',
            field=models.CharField(help_text='The XPath at which the node to be edited can be found.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='xmleditform',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
